//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newnwe {
	
	
	public partial class Edit {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.GridView GridView1;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.TextBox TextBox2;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.TextBox TextBox3;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Label Label4;
		
		protected System.Web.UI.WebControls.Label Label5;
		
		protected System.Web.UI.WebControls.TextBox TextBox5;
		
		protected System.Web.UI.WebControls.Label Label6;
		
		protected System.Web.UI.WebControls.TextBox TextBox6;
		
		protected System.Web.UI.WebControls.Label Label7;
		
		protected System.Web.UI.WebControls.TextBox TextBox7;
		
		protected System.Web.UI.WebControls.Label Label8;
		
		protected System.Web.UI.WebControls.TextBox TextBox8;
		
		protected System.Web.UI.WebControls.Label Label9;
		
		protected System.Web.UI.WebControls.TextBox TextBox9;
		
		protected System.Web.UI.WebControls.Button Button2;
	}
}
